[package]
name = "discord-mediaplayer-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.6"
dbus-tokio = "0.7.5"
tokio = "1.22.0"
